package com.terraforming.ares.model.turn;

/**
 * Created by oleksii.nikitin
 * Creation date 25.04.2022
 */
public enum TurnType {
    PICK_CORPORATION,
    PICK_PHASE,
    BUILD_GREEN_PROJECT,
    SELL_CARDS,
    SELL_VP,
    SELL_CARDS_LAST_ROUND,
    SKIP_TURN,
    BUILD_BLUE_RED_PROJECT,
    PERFORM_BLUE_ACTION,
    COLLECT_INCOME,
    DRAFT_CARDS,
    PICK_EXTRA_BONUS_SECOND_PHASE,
    PLANT_FOREST,
    INCREASE_TEMPERATURE,
    STANDARD_PROJECT,
    EXCHANGE_HEAT,
    DISCARD_CARDS,
    GAME_END_CONFIRM,
    GAME_END,
    UNMI_RT,
    MULLIGAN,
    RESOLVE_PERSISTENT_ALL,
    RESOLVE_IMMEDIATE_ALL,
    RESOLVE_PERSISTENT_WITH_CHOICE,
    RESOLVE_IMMEDIATE_WITH_CHOICE,
    DRAW_CRYSIS_CARD,
    PLANTS_TO_CRISIS_TOKEN,
    HEAT_TO_CRISIS_TOKEN,
    CARDS_TO_CRISIS_TOKEN,
    CRISIS_CHOOSE_DUMMY_HAND,
    CRISIS_VP_TO_TOKEN,
    RESOLVE_OCEAN_DETRIMENT
}
