package com.terraforming.ares.model;

/**
 * Created by oleksii.nikitin
 * Creation date 03.03.2023
 */
public enum CrysisCardAction {
    ATMOSPHERE_RUPTURE,
    CATASTROPHIC_EROSION,
    EMERGENCY_SHELTERS,
    BARREN_CRATER,
    BIODIVERSITY_LOSS,
    GREENHOUSE_GAS_DEGRADATION,
    DUST_CLOUDS,
    SEISMIC_AFTERSHOCKS,
    DISRUPTED_SUPPLY_LINES,
    ATMOSPHERIC_ESCAPE,
    IONOSPHERIC_TEAR,
    IMPACT_DESERT,
    REGLACIATION,
    CROP_FAILURES,
    LOCALIZED_TSUNAMI,
    INFRASTRUCTURE_COLLAPSE,
    COLLAPSING_CITIES,
    PLAY_AND_DISCARD_CRYSIS
}
