package com.terraforming.ares.model;

/**
 * Created by oleksii.nikitin
 * Creation date 05.05.2022
 */
public enum SpecialEffect {
    AMPLIFY_GLOBAL_REQUIREMENT,
    ADVANCED_ALLOYS,
    ASSEMBLY_LINES,
    SOLD_CARDS_COST_1_MC_MORE,
    EXOCORP_SOLD_CARDS_COST_1_MC_MORE,
    EARTH_CATAPULT_DISCOUNT_2,
    GMO_CONTRACT_DISCOUNT_3,
    ENERGY_SUBSIDIES_DISCOUNT_4,
    INTERPLANETARY_CONFERENCE,
    MEDIA_GROUP,
    RESEARCH_OUTPOST_DISCOUNT_1,
    RESTRUCTURED_RESOURCES,
    STANDARD_TECHNOLOGY,
    DEV_TECHS_DISCOUNT,
    LAUNCH_STAR_DISCOUNT,
    EXTENDED_RESOURCES,
    INTERPLANETARY_RELATIONS,
    INTERNS,
    UNITED_PLANETARY_ALLIANCE,
    IO_MINING_INDUSTRIES,
    TORGATE_ENERGY_DISCOUNT,
    TERACTOR_EARTH_DISCOUNT,
    THARSIS_REPUBLIC,
    CREDICOR_DISCOUNT,
    PHOBOLOG,
    ECOLINE_DISCOUNT,
    INTERPLANETARY_CINEMATICS_DISCOUNT,
    COMMUNICATIONS_STREAMLINING,
    ORBITAL_OUTPOST_DISCOUNT,
    BACTERIAL_AGGREGATES,
    HOHMANN_DISCOUNT_1,
    APOLLO_INDUSTRIES,
    NEBU_LABS_CORPORATION,
    MARTIAN_LUMBER
}
