package com.terraforming.ares.model;

/**
 * Created by oleksii.nikitin
 * Creation date 25.04.2022
 */
public enum StateType {
    PICK_CORPORATIONS,
    PICK_PHASE,
    BUILD_GREEN_PROJECTS,
    BUILD_BLUE_RED_PROJECTS,
    PERFORM_BLUE_ACTION,
    COLLECT_INCOME,
    DRAFT_CARDS,
    SELL_EXTRA_CARDS,
    GAME_END,
    RESOLVE_PERSISTENT_ALL,
    RESOLVE_CRYSIS_WITH_CHOICE,
    DRAW_CRYSIS_CARD,
    CRISIS_DRAW_DUMMY_HAND,
    CRISIS_END_STEP,
    RESOLVE_OCEAN_DETRIMENT
}
